### ISSUE TITLE
Entry fails to save when embed field contains an instagram image with emojis in the caption

### ISSUE THREAD

**Issue by dohayon** [newism/craft3-fields#22]
<img width="481" alt="screenshot 2018-02-26 17 48 13" src="https://user-images.githubusercontent.com/5711643/36700368-727f544c-1b1d-11e8-8cf0-0f8ba535ed8f.png">

**Comment by leevigraham** [comment]
Interesting… I'll check with @brandonkelly how craft handles emojis

**Comment by brandonkelly** [comment]
@leevigraham Craft emoji support has 3 facets:

- `craft\helpers\StringHelper::encodeMb4()` will HTML-encode all 4(+)-byte characters. Only con is that they get converted to HTML entities, which may not be desired if the string isn’t HTML.

- `LitEmoji\LitEmoji::unicodeToShortcode()` will convert most emoji to `:shortcodes`; and `shortcodeToUnicode()` will convert `:shortcodes:` back to the unicode emjoi chars. Only con is that any unsupported emoji characters will not be touched, which could still lead to errors.

- PostgreSQL has no trouble with emoji, so if you have a site that needs good emoji support, you should use that if at all possible instead of MySQL.

**Comment by leevigraham** [comment]
Sounds like `craft\helpers\StringHelper::encodeMb4()` is the best option here given the output will always be html.

**Comment by leevigraham** [comment]
Example URL: https://www.instagram.com/p/BfYPK64FFe6/?taken-by=leevigraham

**Comment by leevigraham** [comment]
Looking at the craft code it looks like fields are using `encodeMb4()` in the fckeditor plugin

``` 
if (Craft::$app->getDb()->getIsMysql()) {
    // Encode any 4-byte UTF-8 characters.
    $value = StringHelper::encodeMb4($value);
}
```

The EmbedModel implements `JsonSerializable` which means it's skipped by Crafts `serializeValue` method…

TBC.

**Comment by leevigraham** [comment]
@brandonkelly what is Craft's position on emoji support? If support is only guaranteed on a DB level then I'm tempted to follow suit.

**Comment by leevigraham** [comment]
@dohayon, I've implemented LitEmoji encoding / decoding.

**Comment by leevigraham** [comment]
Related: https://github.com/craftcms/cms/issues/2527
